### ISSUE TITLE
uninitialized constant Psych::ENGINE (NameError)

### ISSUE THREAD

**Issue by EMRJ** [rubycas/rubycas-server#250] opened 2015-10-19 07:26 UTC
When I run bundle exec rubycas-server -c config.yml got the following error

=> Using custom config file "config.yml"
/home/mathan/.rvm/gems/ruby-2.2.0/gems/r18n-core-1.1.11/lib/r18n-core/yaml_methods.rb:34:in `detect_yaml_private_type': uninitialized constant Psych::ENGINE (NameError)
	from /home/mathan/.rvm/gems/ruby-2.2.0/gems/r18n-core-1.1.11/lib/r18n-core/yaml_loader.rb:42:in `initialize'
	from /home/mathan/.rvm/gems/ruby-2.2.0/gems/r18n-core-1.1.11/lib/r18n-core.rb:160:in `new'
	from /home/mathan/.rvm/gems/ruby-2.2.0/gems/r18n-core-1.1.11/lib/r18n-core.rb:160:in `<module:R18n>'
	from /home/mathan/.rvm/gems/ruby-2.2.0/gems/r18n-core-1.1.11/lib/r18n-core.rb:40:in `<top (required)>'
	from /home/mathan/.rvm/gems/ruby-2.2.0/gems/sinatra-r18n-1.1.11/lib/sinatra/r18n.rb:22:in `<top (required)>'
	from /home/mathan/work/projects/p/rubycas-server/lib/casserver/base.rb:2:in `<top (required)>'
	from /home/mathan/work/projects/p/rubycas-server/lib/casserver/server.rb:3:in `<top (required)>'
	from /home/mathan/work/projects/p/rubycas-server/lib/casserver.rb:18:in `require'
	from /home/mathan/work/projects/p/rubycas-server/lib/casserver.rb:18:in `<top (required)>'
	from /home/mathan/work/projects/p/rubycas-server/bin/rubycas-server:28:in `require'
	from /home/mathan/work/projects/p/rubycas-server/bin/rubycas-server:28:in `<top (required)>'
	from /home/mathan/.rvm/gems/ruby-2.2.0/bin/rubycas-server:23:in `load'
	from /home/mathan/.rvm/gems/ruby-2.2.0/bin/rubycas-server:23:in `<main>'
	from /home/mathan/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/mathan/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>

**Comment by mongeta** [comment] 2015-11-28 15:50
+1

I'm having the same problem, any work-arounds?

thanks

**Comment by lucaspiller** [comment] 2015-12-03 13:33
This is a duplicate of https://github.com/rubycas/rubycas-server/issues/242, the problem is one of the dependencies doesn't support Ruby 2.2. If you downgrade to Ruby 2.1.5 it will work fine.

**Closed** 2015-12-07 15:04 UTC

**Comment by jordinl** [comment] 2016-04-27 09:39
@lucaspiller how is this a solution?

**Comment by HectorOrdonez** [comment] 2017-01-09 12:53
I am going through a lot of pain right now.

**Comment by ribanez7** [comment] 2017-01-10 07:41
I have this problem solved locally; will merge my code and send a PR as soon as possible during this month.

**Comment by Skill-Zozo** [comment] 2017-01-10 12:23
so much pain

**Comment by pikitgb** [comment] 2017-01-31 20:48
Any solution for this ? Downgrading the ruby version solves the issue ?

**Comment by HectorOrdonez** [comment] 2017-01-31 22:07
@pikitgb Yes. Using ruby "1.9.3" fixed THIS problem. Then I had others.
I recommend, if possible, running away from this. Installing CASino atm.

**Comment by pikitgb** [comment] 2017-01-31 22:20
@HectorOrdonez thanks! I figure that out 45 mins ago lol. I'm checking CASino. is working ok until now.. besides therubyracer and libv8 headache. Thanks.

**Comment by ribanez7** [comment] 2017-02-01 07:05
The only problem is on the use of the R18n gem. If you replace all the R18n related lines with the I18n library it works perfectly with all newest ruby versions.
Still haven't got the time to do so on the repo...

**Comment by sg552** [comment] 2017-11-21 02:41
still got this problem under ruby 2.2.4
